/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainPackage;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.regex.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class TrainerLoginNew extends javax.swing.JFrame {

    /**
     * Creates new form TrainerLoginNew
     */
    
    private static final String HOST = "jdbc:derby://localhost:1527/SportsAcademy";
    private static final String USERNAME = "mydb";
    private static final String PASSWORD = "admin";
    private static boolean invalid = true;
    private String trainer;
    private String TID;
    
    public TrainerLoginNew() {
        initComponents();
        this.setLocationRelativeTo(null);
        clearData();
        trainername.setText("Error!!!");
        invalid = true;
        profilePanel.setVisible(true);
        performancePanel.setVisible(false);
        passwordPanel.setVisible(false);
    }

    public TrainerLoginNew(String userName, String trainerName) {
        this();
        invalid = false;
        trainer = trainerName;
        TID = userName;
        trainername.setText("Hi, "+trainer+"!");
        getData();
    }
        
    private void clearData() {
        DefaultTableModel model1 = (DefaultTableModel) profileTable.getModel();
        model1.setRowCount(0);
        DefaultTableModel model2 = (DefaultTableModel) performanceTable.getModel();
        model2.setRowCount(0);
    }
    
    private void getData() {
        clearData();//Clear the table befor rendering new data
        if(invalid) {
            return;
        } else {
            DefaultTableModel model1 = (DefaultTableModel) profileTable.getModel();
            try{
                Connection con = DriverManager.getConnection(HOST,USERNAME,PASSWORD);
                Statement stmt = con.createStatement();
                String query = "SELECT * FROM trainer WHERE trainerid = '"+TID+"'";
                ResultSet rs = stmt.executeQuery(query);
                while(rs.next()) {
                    model1.addRow(new Object[]{"Trainer ID", rs.getString("trainerid")});
                    model1.addRow(new Object[]{"Name", rs.getString("name")});
                    model1.addRow(new Object[]{"Contact", rs.getString("contact")});
                    model1.addRow(new Object[]{"Address", rs.getString("address")});
                    model1.addRow(new Object[]{"Email", rs.getString("email")});
                    model1.addRow(new Object[]{"Sport", rs.getString("sport")});
                }
            }
            catch(Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        trainername = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        profileToggle = new javax.swing.JLabel();
        performanceToggle = new javax.swing.JLabel();
        passwordToggle = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        profilePanel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        profileTable = new javax.swing.JTable();
        performancePanel = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        performanceTable = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        regnoUpdate = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        sportUpdate = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        gradeUpdate = new javax.swing.JTextField();
        submitUpdate = new javax.swing.JButton();
        passwordPanel = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        newPass = new javax.swing.JPasswordField();
        confNewPass = new javax.swing.JPasswordField();
        submitPassword = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setBackground(new java.awt.Color(240, 240, 255));
        jPanel6.setAutoscrolls(true);
        jPanel6.setPreferredSize(new java.awt.Dimension(1241, 1101));

        jPanel1.setBackground(new java.awt.Color(55, 128, 128));
        jPanel1.setPreferredSize(new java.awt.Dimension(471, 85));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(">>||WELCOME TO TRAINER LOGIN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(240, 240, 255));

        trainername.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        trainername.setForeground(new java.awt.Color(54, 82, 122));
        trainername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        trainername.setText("Hi, Trainer!");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TRAINER'S RECORD");

        logout.setFont(new java.awt.Font("Verdana", 3, 20)); // NOI18N
        logout.setForeground(new java.awt.Color(0, 102, 0));
        logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logout.setText("LogOut");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(trainername, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(trainername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addComponent(logout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(265, 500));

        profileToggle.setBackground(new java.awt.Color(0, 51, 102));
        profileToggle.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        profileToggle.setForeground(new java.awt.Color(0, 51, 102));
        profileToggle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileToggle.setText("My Profile");
        profileToggle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileToggleMouseClicked(evt);
            }
        });

        performanceToggle.setBackground(new java.awt.Color(0, 51, 102));
        performanceToggle.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        performanceToggle.setForeground(new java.awt.Color(0, 51, 102));
        performanceToggle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        performanceToggle.setText("View Students");
        performanceToggle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                performanceToggleMouseClicked(evt);
            }
        });

        passwordToggle.setBackground(new java.awt.Color(0, 51, 102));
        passwordToggle.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        passwordToggle.setForeground(new java.awt.Color(0, 51, 102));
        passwordToggle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordToggle.setText("Change Password");
        passwordToggle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordToggleMouseClicked(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(55, 128, 128));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(profileToggle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(performanceToggle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(passwordToggle, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(profileToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(performanceToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(194, 232, 194));

        profilePanel.setOpaque(false);

        jPanel8.setBackground(new java.awt.Color(250, 250, 250));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(97, 85, 82));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PROFILE INFORMATION");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jScrollPane1.setBorder(null);

        profileTable.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        profileTable.setForeground(new java.awt.Color(0, 51, 102));
        profileTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "FIELD", "INFORMATION"
            }
        ));
        profileTable.setFocusable(false);
        profileTable.setIntercellSpacing(new java.awt.Dimension(3, 5));
        profileTable.setOpaque(false);
        profileTable.setRowHeight(35);
        profileTable.setShowVerticalLines(false);
        jScrollPane1.setViewportView(profileTable);
        if (profileTable.getColumnModel().getColumnCount() > 0) {
            profileTable.getColumnModel().getColumn(0).setMinWidth(150);
            profileTable.getColumnModel().getColumn(0).setPreferredWidth(200);
            profileTable.getColumnModel().getColumn(0).setMaxWidth(250);
            profileTable.getColumnModel().getColumn(1).setMinWidth(500);
            profileTable.getColumnModel().getColumn(1).setMaxWidth(1000);
        }

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        performancePanel.setOpaque(false);

        jPanel14.setBackground(new java.awt.Color(250, 250, 250));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(97, 85, 82));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("STUDENT'S DETAILS");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jScrollPane2.setBackground(new java.awt.Color(194, 232, 194));
        jScrollPane2.setBorder(null);
        jScrollPane2.setColumnHeader(null);
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        performanceTable.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        performanceTable.setForeground(new java.awt.Color(0, 51, 102));
        performanceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "REG. NO.", "NAME", "CONTACT", "SPORT", "GRADE"
            }
        ));
        performanceTable.setIntercellSpacing(new java.awt.Dimension(3, 5));
        performanceTable.setMinimumSize(new java.awt.Dimension(575, 45));
        performanceTable.setOpaque(false);
        performanceTable.setRowHeight(35);
        performanceTable.setShowVerticalLines(false);
        performanceTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                performanceTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(performanceTable);
        if (performanceTable.getColumnModel().getColumnCount() > 0) {
            performanceTable.getColumnModel().getColumn(0).setMinWidth(100);
            performanceTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            performanceTable.getColumnModel().getColumn(1).setMinWidth(175);
            performanceTable.getColumnModel().getColumn(1).setPreferredWidth(200);
            performanceTable.getColumnModel().getColumn(2).setMinWidth(150);
            performanceTable.getColumnModel().getColumn(2).setPreferredWidth(150);
            performanceTable.getColumnModel().getColumn(3).setMinWidth(150);
            performanceTable.getColumnModel().getColumn(3).setPreferredWidth(150);
            performanceTable.getColumnModel().getColumn(4).setMinWidth(50);
            performanceTable.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(128, 66, 66));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Enter/Update Grade");
        jLabel8.setOpaque(true);

        jPanel7.setOpaque(false);

        jLabel13.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(67, 42, 35));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel13.setText("Registration No. :");
        jLabel13.setToolTipText("");

        jLabel14.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(67, 42, 35));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel14.setText("Sport");
        jLabel14.setToolTipText("");

        jLabel15.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(67, 42, 35));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel15.setText("Grade :");
        jLabel15.setToolTipText("");

        submitUpdate.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        submitUpdate.setForeground(new java.awt.Color(56, 32, 32));
        submitUpdate.setText("Submit");
        submitUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sportUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(regnoUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(gradeUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(418, 418, 418))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(regnoUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sportUpdate))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gradeUpdate))
                .addGap(18, 18, 18)
                .addComponent(submitUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout performancePanelLayout = new javax.swing.GroupLayout(performancePanel);
        performancePanel.setLayout(performancePanelLayout);
        performancePanelLayout.setHorizontalGroup(
            performancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(performancePanelLayout.createSequentialGroup()
                .addGroup(performancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(performancePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(performancePanelLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 58, Short.MAX_VALUE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        performancePanelLayout.setVerticalGroup(
            performancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(performancePanelLayout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        passwordPanel.setOpaque(false);

        jPanel13.setBackground(new java.awt.Color(250, 250, 250));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(97, 85, 82));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("UPDATE PASSWORD");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jLabel10.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(67, 42, 35));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("New Password :");
        jLabel10.setToolTipText("");

        jLabel11.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(67, 42, 35));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("Confirm New Password :");
        jLabel11.setToolTipText("");

        submitPassword.setFont(new java.awt.Font("Lucida Sans", 1, 16)); // NOI18N
        submitPassword.setForeground(new java.awt.Color(56, 32, 32));
        submitPassword.setText("Submit");
        submitPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitPasswordMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout passwordPanelLayout = new javax.swing.GroupLayout(passwordPanel);
        passwordPanel.setLayout(passwordPanelLayout);
        passwordPanelLayout.setHorizontalGroup(
            passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(passwordPanelLayout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addGroup(passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(passwordPanelLayout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(newPass, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(passwordPanelLayout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(18, 18, 18)
                            .addComponent(confNewPass)))
                    .addComponent(submitPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        passwordPanelLayout.setVerticalGroup(
            passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordPanelLayout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newPass, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(passwordPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(confNewPass, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(submitPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(profilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(performancePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(passwordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(profilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(performancePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1221, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1360, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 1221, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 1519, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profileToggleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileToggleMouseClicked
        // TODO add your handling code here:
        clearData();//Clear the table befor rendering new data
        if(invalid) {
            return;
        } else {
            profilePanel.setVisible(true);
            performancePanel.setVisible(false);
            passwordPanel.setVisible(false);
            DefaultTableModel model1 = (DefaultTableModel) profileTable.getModel();
            try{
                Connection con = DriverManager.getConnection(HOST,USERNAME,PASSWORD);
                Statement stmt = con.createStatement();
                String query = "SELECT * FROM trainer WHERE trainerid = '"+TID+"'";
                ResultSet rs = stmt.executeQuery(query);
                while(rs.next()) {
                    model1.addRow(new Object[]{"Trainer ID", rs.getString("trainerid")});
                    model1.addRow(new Object[]{"Name", rs.getString("name")});
                    model1.addRow(new Object[]{"Contact", rs.getString("contact")});
                    model1.addRow(new Object[]{"Address", rs.getString("address")});
                    model1.addRow(new Object[]{"Email", rs.getString("email")});
                    model1.addRow(new Object[]{"Sport", rs.getString("sport")});
                }
            }
            catch(Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_profileToggleMouseClicked

    private void performanceToggleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_performanceToggleMouseClicked
        // TODO add your handling code here:
        clearData();//Clear the table befor rendering new data
        if(invalid) {
            return;
        } else {
            profilePanel.setVisible(false);
            performancePanel.setVisible(true);
            passwordPanel.setVisible(false);
            DefaultTableModel model2 = (DefaultTableModel) performanceTable.getModel();
            try{
                Connection con = DriverManager.getConnection(HOST,USERNAME,PASSWORD);
                Statement stmt = con.createStatement();
                String query1 = "SELECT regno, sport, grade FROM performance WHERE trainer_name = '"+TID+"-"+trainer+"'";
                ResultSet rs1 = stmt.executeQuery(query1);
                while(rs1.next()) {
                    String Reg = rs1.getString("regno");
                    String Spo = rs1.getString("sport");
                    String Gra = rs1.getString("grade");
                    try {
                        Statement stmt2 = con.createStatement();
                        String query2 = "SELECT name, contact FROM student WHERE regno = '"+Reg+"'";
                        ResultSet rs2 = stmt2.executeQuery(query2);
                        while(rs2.next()) {
                            model2.addRow(new Object[]{Reg, rs2.getString("name"), rs2.getString("contact"), Spo, Gra});
                        }
                        stmt2.close();
                    } catch(Exception e) {
                        JOptionPane.showMessageDialog(null, "Inside"+e);
                    }
                }
            }
            catch(Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_performanceToggleMouseClicked

    private void passwordToggleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordToggleMouseClicked
        // TODO add your handling code here:
        clearData();//Clear the table befor rendering new data
        if(invalid) {
            return;
        } else {
            profilePanel.setVisible(false);
            performancePanel.setVisible(false);
            passwordPanel.setVisible(true);
        }
    }//GEN-LAST:event_passwordToggleMouseClicked

    private void performanceTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_performanceTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) performanceTable.getModel();
        int rowIndex = performanceTable.getSelectedRow();
        regnoUpdate.setText(model.getValueAt(rowIndex, 0).toString());
        sportUpdate.setText(model.getValueAt(rowIndex, 3).toString());
    }//GEN-LAST:event_performanceTableMouseClicked

    private void submitPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitPasswordMouseClicked
        // TODO add your handling code here:
        if(invalid) {
            return;
        } else {
            String pass1 = newPass.getText().toString();
            String pass2 = confNewPass.getText().toString();
            if(pass1.equals(pass2)) {
                if(pass1.length()>=8 && pass1.length()<=25) {
                    Pattern p = Pattern.compile("^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{8,25}$");
                    Matcher m = p.matcher(pass1);
                    if(m.matches()) {
                        try {
                            Connection con = DriverManager.getConnection(HOST,USERNAME,PASSWORD);
                            Statement stmt = con.createStatement();
                            String query1 = "UPDATE trainer SET password = '"+pass1+"' WHERE trainerid = '"+TID+"'";
                            stmt.execute(query1);
                            JOptionPane.showMessageDialog(null, "Password updated successfully.\nLogin again with new password.");
                            this.dispose();
                            LandingPage loggedout = new LandingPage("trainer");
                            loggedout.setVisible(true);
                        } catch(Exception e) {
                            JOptionPane.showMessageDialog(null, e);
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Password must contain atleast one lowercase letter, uppercase letter, one digit and one Special character.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Password must be 8 to 25 characters long.");
                }
            } else {
                JOptionPane.showMessageDialog(null, "New Password and Confirm New Password must be same.");
            }
        }
    }//GEN-LAST:event_submitPasswordMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        this.dispose();
        LandingPage loggedout = new LandingPage("trainer");
        loggedout.setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void submitUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitUpdateActionPerformed
        // TODO add your handling code here:
        if(invalid) {
            return;
        } else {
            String Reg = regnoUpdate.getText();
            String Spo = sportUpdate.getText();
            String Gra = gradeUpdate.getText();
            if(!Reg.equals("") || !Spo.equals("") || !Gra.equals("")) {
                try {
                    Connection con = DriverManager.getConnection(HOST,USERNAME,PASSWORD);
                    Statement stmt = con.createStatement();
                    String query = "UPDATE performance SET grade = '"+Gra+"' WHERE regno = '"+Reg+"' AND sport = '"+Spo+"'";
                    stmt.execute(query);
                    JOptionPane.showMessageDialog(null, "Grade updated successfully...");
                    clearData();
                    DefaultTableModel model2 = (DefaultTableModel) performanceTable.getModel();
                    try{
                        Statement stmt1 = con.createStatement();
                        String query1 = "SELECT regno, sport, grade FROM performance WHERE trainer_name = '"+TID+"-"+trainer+"'";
                        ResultSet rs1 = stmt1.executeQuery(query1);
                        while(rs1.next()) {try {
                                Statement stmt2 = con.createStatement();
                                String query2 = "SELECT name, contact FROM student WHERE regno = '"+rs1.getString("regno")+"'";
                                ResultSet rs2 = stmt2.executeQuery(query2);
                                while(rs2.next()) {
                                    model2.addRow(new Object[]{rs1.getString("regno"), rs2.getString("name"), rs2.getString("contact"), rs1.getString("sport"), rs1.getString("grade")});
                                }
                                stmt2.close();
                            } catch(Exception e) {
                                JOptionPane.showMessageDialog(null, "Inside-\n"+e);
                            }
                        }
                    }
                    catch(Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                } catch(Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please enter Registration number, Sport and Grade to be updated.");
            }
        }
    }//GEN-LAST:event_submitUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainerLoginNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainerLoginNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainerLoginNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainerLoginNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrainerLoginNew().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confNewPass;
    private javax.swing.JTextField gradeUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel logout;
    private javax.swing.JPasswordField newPass;
    private javax.swing.JPanel passwordPanel;
    private javax.swing.JLabel passwordToggle;
    private javax.swing.JPanel performancePanel;
    private javax.swing.JTable performanceTable;
    private javax.swing.JLabel performanceToggle;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JTable profileTable;
    private javax.swing.JLabel profileToggle;
    private javax.swing.JTextField regnoUpdate;
    private javax.swing.JTextField sportUpdate;
    private javax.swing.JButton submitPassword;
    private javax.swing.JButton submitUpdate;
    private javax.swing.JLabel trainername;
    // End of variables declaration//GEN-END:variables
}
